### ISSUE TITLE
Can't get  node-red producer out  message out to cmd consumer

### ISSUE THREAD

**Issue by Isuru40** [peterprib/node-red-contrib-kafka-manager#2] opened 2019-10-27 17:33 UTC
I configured producer node in node-red and inject payload.After deployment producer node shows connected to broker and node-red cmd interface also generating status as sending messages. But i consumed message by cmd. It is printed out message is null? What was the issue?

**Comment by peterprib** [comment] 2019-10-28 11:36
Need a bit more clarity on your problem.   If I understand your problem you have inserted message using node-red and which appears to have said message accepted and published on Kafka.  This message had a payload with contained what type of data?  Could you detail total message content.  Plus configuration of producer.  You have used Kafka command line command to consume message and a message was returned that indicated an empty message.  Could you detail command(s) used to consume message.  When you say null, is this an message of zero length or a message containing char considered to be null.  That is message length greater than zero and you have examined the char content and it contains character representation of null rather than non printable characters.

**Comment by Isuru40** [comment] 2019-10-29 01:11
![diagram](https://user-images.githubusercontent.com/25480142/67728706-25160200-fa14-11e9-8716-607b7cd6892a.png)

This is the my diagram 

here is my inject node configuration.

![inject-node-kafka](https://user-images.githubusercontent.com/25480142/67728933-2267dc80-fa15-11e9-8253-3994072f09a7.png)

nodered is my topic i used.here is the producer node configurations.

![producer node](https://user-images.githubusercontent.com/25480142/67729058-a752f600-fa15-11e9-87a4-0a73c17d58bb.png)

Broker configuration.

![broker configuration](https://user-images.githubusercontent.com/25480142/67729222-3fe97600-fa16-11e9-8d8e-8a2a16d5677e.png)

![broker configuration-options](https://user-images.githubusercontent.com/25480142/67729287-7a531300-fa16-11e9-8fa0-819ef2ce0fe6.png)

**kafka-console-consumer.bat --bootstrap-server localhost:9092 --topic nodered --from-beginning**
This is the command i opened cmd and its keep printing **null**.Could you please check those configurations.My kafka server and node-red server running on same laptop.

**Comment by peterprib** [comment] 2019-10-29 10:11
Think the issue is the payload is in javascript number format thus message being printed does not show as character.  That is, not a null message but a bit pattern representing a number that isn't visible as printable character as incorrectly typed as string.  Hex dump is required of message which would require the use of --formatter parameter.  This would be expected behavior as it is sending payload as given and I suggest correct behavior. When I get a chance I will validate my assumption.

**Comment by peterprib** [comment] 2019-10-31 07:28
Found a bug that may explain matters.  I had assumed that "returns null" meant message returns null rather than no messages returned.  To build resilience if the producer loses connection or waiting on initial connection it queues messages until the connection is established or re-established.  It is falsely reporting producer as being connected and actively delivering messages into Kafka.  I will fix so it correctly reports state of producer and if it is queuing messages.

**Comment by peterprib** [comment] 2019-11-01 22:22
Have published a fix for a publish node not indicating it is in a problem state and queuing message.  Have noticed that when a producer initially connects there is an empty message generated.  Haven't noticed this behavior before.  Will investigate what is causing this and try and get fixed.

**Comment by peterprib** [comment] 2019-11-02 03:17
Have just published a fix for null message on connection plus bug with error and retry logic on lost connection by the producer.  Closing as this should have solved your issue.

**Closed by peterprib** 2019-11-02 03:17 UTC
